"""Ingestion agent: extract, resolve time and entities, reconcile and enrich saves (S2)."""

from secondmind.ingestion.ack import AckFacts, acknowledge, refusal, summarise_commit
from secondmind.ingestion.entities import (
    CLOSE_LABELS,
    SELF_WORDS,
    EntityPlan,
    match_entities,
    mentions_in,
    resolve_entities,
)
from secondmind.ingestion.normalise import BUILTIN, Term, match_key, normalise, slugify, terms_for
from secondmind.ingestion.offline import load_replay, offline_responders, replay_key
from secondmind.ingestion.pipeline import (
    EnrichVars,
    ExtractionInvalidError,
    ExtractVars,
    IngestContext,
    IngestionPipeline,
    IngestOutcome,
    IngestSettings,
    ReconcileVars,
    ResolveVars,
)
from secondmind.ingestion.reconcile import Decision, Draft, Reconciler, same_value
from secondmind.ingestion.schemas import (
    Attribute,
    EnrichedMemory,
    EnrichOutput,
    EntityChoice,
    EntityRef,
    ExtractedEntity,
    ExtractOutput,
    IntentOutput,
    MemoryLinkOut,
    NotWritten,
    ProposedMemory,
    Rating,
    ReconcileChoice,
    Relation,
    Reminder,
    StatementValue,
    TimeExpression,
    validate_extraction,
)
from secondmind.ingestion.steps import ModelSteps, RecordModelCall, cosine
from secondmind.ingestion.time import (
    PARTS,
    REMINDER_HOUR,
    Direction,
    Lead,
    Resolved,
    TurnNow,
    UnresolvableTimeError,
    Window,
    WindowDirection,
    reminder_time,
    resolve,
    resolve_lead,
    resolve_window,
    validate_rrule,
)

__all__ = [
    "BUILTIN",
    "CLOSE_LABELS",
    "PARTS",
    "REMINDER_HOUR",
    "SELF_WORDS",
    "AckFacts",
    "Attribute",
    "Decision",
    "Direction",
    "Draft",
    "EnrichOutput",
    "EnrichVars",
    "EnrichedMemory",
    "EntityChoice",
    "EntityPlan",
    "EntityRef",
    "ExtractOutput",
    "ExtractVars",
    "ExtractedEntity",
    "ExtractionInvalidError",
    "IngestContext",
    "IngestOutcome",
    "IngestSettings",
    "IngestionPipeline",
    "IntentOutput",
    "Lead",
    "MemoryLinkOut",
    "ModelSteps",
    "NotWritten",
    "ProposedMemory",
    "Rating",
    "ReconcileChoice",
    "ReconcileVars",
    "Reconciler",
    "RecordModelCall",
    "Relation",
    "Reminder",
    "ResolveVars",
    "Resolved",
    "StatementValue",
    "Term",
    "TimeExpression",
    "TurnNow",
    "UnresolvableTimeError",
    "Window",
    "WindowDirection",
    "acknowledge",
    "cosine",
    "load_replay",
    "match_entities",
    "match_key",
    "mentions_in",
    "normalise",
    "offline_responders",
    "refusal",
    "reminder_time",
    "replay_key",
    "resolve",
    "resolve_entities",
    "resolve_lead",
    "resolve_window",
    "same_value",
    "slugify",
    "summarise_commit",
    "terms_for",
    "validate_extraction",
    "validate_rrule",
]
