/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Process is alive (no dependencies checked).
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Database (schema at head, app role under RLS), Redis, and provider config.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Create or reuse the dev user (or the one named in the body) and their private workspace;
         *     set the session cookie.
         */
        post: operations["dev_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/held-writes/{held_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Held Write
         * @description Apply a held write as a new turn (with its own diff, so undo still works).
         */
        post: operations["confirm_held_write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/held-writes/{held_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Held Write */
        post: operations["reject_held_write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Usage
         * @description The signed-in user's token quota: tier, limit, used and remaining (FR-12.5).
         *     Read only: enforcement arrives in S4.
         */
        get: operations["my_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Build, routing and config hash this process runs with (FR-19.2).
         */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turn */
        get: operations["get_turn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Turn Events
         * @description The turn's structured events, in order: the glass box's source of truth (FR-9.2).
         */
        get: operations["get_turn_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turns/{turn_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Turn
         * @description Revert every memory write the turn made, as a new turn with its own diff (FR-10.1).
         *     Undoing an undo turn is a redo.
         */
        post: operations["undo_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/held-writes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Held Writes */
        get: operations["list_held_writes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Turns
         * @description Conversation history for a workspace, newest first (FR-1.6).
         */
        get: operations["list_turns"];
        put?: never;
        /**
         * Create Turn
         * @description Send a message; the reply streams back as server-sent events.
         */
        post: operations["create_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentStep
         * @description The agent steps a turn can report, in the UI's catalogue (docs/design/system.md §8).
         *
         *     ``plan``, ``search``, ``rank``, ``triggers`` (S3) and ``fetch`` (S4) are reserved: in the
         *     schema so the UI's catalogue is complete, not emitted yet.
         * @enum {string}
         */
        AgentStep: "understand" | "extract" | "dates" | "entities" | "reconcile" | "enrich" | "guard" | "save" | "answer" | "undo" | "confirm" | "plan" | "search" | "rank" | "triggers" | "fetch";
        /** CheckOut */
        CheckOut: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * Classification
         * @description What one proposed memory was taken to be.
         */
        Classification: {
            /** Category */
            category?: string | null;
            /** Format */
            format?: string | null;
            kind: components["schemas"]["Kind"];
            /** Label */
            label: string;
            /** @default archive */
            layer: components["schemas"]["Layer"];
            /** @default asserted */
            modality: components["schemas"]["Modality"];
            /** Rationale */
            rationale: string;
            /** @default normal */
            sensitivity: components["schemas"]["Sensitivity"];
            /** State */
            state?: string | null;
            /** Subtype */
            subtype?: string | null;
        };
        /** CreateTurnIn */
        CreateTurnIn: {
            /** Message */
            message: string;
        };
        /**
         * DecisionEvent
         * @description Decision panel: kinds, date and entity resolutions, reconciliation, rationale.
         */
        DecisionEvent: {
            /**
             * Classifications
             * @default []
             */
            classifications: components["schemas"]["Classification"][];
            /**
             * Decided By
             * @description step -> 'provider:model' that made the decision (FR-14.8).
             * @default {}
             */
            decided_by: {
                [key: string]: string;
            };
            /**
             * Entity Resolutions
             * @default []
             */
            entity_resolutions: components["schemas"]["EntityResolution"][];
            /**
             * Normalisations
             * @default []
             */
            normalisations: components["schemas"]["Normalisation"][];
            /**
             * Not Written
             * @default []
             */
            not_written: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Reconciliations
             * @default []
             */
            reconciliations: components["schemas"]["Reconciliation"][];
            /**
             * Rules Applied
             * @default []
             */
            rules_applied: string[];
            /** Summary */
            summary: string;
            /**
             * Time Resolutions
             * @default []
             */
            time_resolutions: components["schemas"]["TimeResolution"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decision";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /**
         * DevLoginIn
         * @description Optional: log in as another dev user (dev auth only), e.g. a fresh one per E2E test.
         */
        DevLoginIn: {
            /** Email */
            email?: string | null;
        };
        /** DiffEntry */
        DiffEntry: {
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FieldChange"][];
            /** Entity Id */
            entity_id?: string | null;
            /** Held Write Id */
            held_write_id?: string | null;
            /** Item Id */
            item_id?: string | null;
            layer: components["schemas"]["Layer"];
            /**
             * Op
             * @enum {string}
             */
            op: "added" | "updated" | "removed" | "superseded" | "fulfilled" | "held" | "not_written" | "conflict";
            /**
             * Reason
             * @default
             */
            reason: string;
            reconcile?: components["schemas"]["ReconcileInfo"] | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Title */
            title: string;
        };
        /** EntityDetailOut */
        EntityDetailOut: {
            entity: components["schemas"]["EntityRecord"];
            /** Item Ids */
            item_ids: string[];
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "self" | "person" | "place" | "org" | "thing" | "work" | "topic" | "project" | "list";
        /** EntityRecord */
        EntityRecord: {
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Turn Id */
            created_by_turn_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Key
             * @default false
             */
            is_key: boolean;
            kind: components["schemas"]["EntityKind"];
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /** Name */
            name: string;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "deleted";
            /** Summary */
            summary?: string | null;
            /** Summary Updated At */
            summary_updated_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By Turn Id */
            updated_by_turn_id: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * EntityResolution
         * @description How a mention ("my wife", "Severance") was matched to an entity, or why one was made.
         */
        EntityResolution: {
            /**
             * Candidates
             * @default []
             */
            candidates: string[];
            /** Created */
            created: boolean;
            /** Display Name */
            display_name: string;
            /** Entity Id */
            entity_id: string | null;
            entity_kind: components["schemas"]["EntityKind"];
            /** Mention */
            mention: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "matched" | "new" | "ambiguous" | "updated";
            /** Rationale */
            rationale: string;
        };
        /**
         * EntityRole
         * @enum {string}
         */
        EntityRole: "about" | "with" | "for" | "by" | "at" | "owner" | "part_of";
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable error code.
             */
            code: string;
            /**
             * Message
             * @description Human-readable, safe to show to users.
             */
            message: string;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * ErrorEvent
         * @description A turn-ending or step-level error, with a stable code and a user-safe message.
         */
        ErrorEvent: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Step */
            step?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FallbackInfo
         * @description Set on a model call that was served by the step's fallback model (FR-14.4).
         */
        FallbackInfo: {
            /** From Model */
            from_model: string;
            /** From Provider */
            from_provider: string;
            /** Reason */
            reason: string;
        };
        /** FieldChange */
        FieldChange: {
            /** After */
            after?: unknown;
            /** Before */
            before?: unknown;
            /** Field */
            field: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * HeldWriteOut
         * @description A write the policy held for confirmation (S2.3).
         */
        HeldWriteOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            layer: components["schemas"]["Layer"];
            /** Reason */
            reason: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved Turn Id */
            resolved_turn_id?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "confirmed" | "rejected";
            /** Title */
            title: string;
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
        };
        /** HeldWritesOut */
        HeldWritesOut: {
            /** Items */
            items: components["schemas"]["HeldWriteOut"][];
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "save" | "recall" | "save_and_recall" | "correct" | "chit_chat";
        /**
         * IntentEvent
         * @description What the agent decided the message is (FR-1.2).
         */
        IntentEvent: {
            /** Confidence */
            confidence: number;
            intent: components["schemas"]["Intent"];
            /** Reason */
            reason: string;
            /**
             * Source
             * @enum {string}
             */
            source: "stub" | "model" | "rule";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "intent";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /**
         * ItemDetailOut
         * @description A plain view of one memory item, its entity roles, links and triggers (S2.11).
         */
        ItemDetailOut: {
            /** Entities */
            entities: components["schemas"]["ItemEntityRecord"][];
            item: components["schemas"]["ItemRecord"];
            /** Links */
            links: components["schemas"]["LinkRecord"][];
            /** Triggers */
            triggers: components["schemas"]["TriggerRecord"][];
        };
        /** ItemEntityRecord */
        ItemEntityRecord: {
            /**
             * Created By Turn Id
             * Format: uuid
             */
            created_by_turn_id: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            role: components["schemas"]["EntityRole"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ItemRecord */
        ItemRecord: {
            /**
             * Access Count
             * @default 0
             */
            access_count: number;
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
            /** Category Id */
            category_id?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Content Ref */
            content_ref?: string | null;
            /** Core Confirmed At */
            core_confirmed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By Turn Id
             * Format: uuid
             */
            created_by_turn_id: string;
            /** Due At */
            due_at?: string | null;
            /**
             * Enrichment
             * @default {}
             */
            enrichment: {
                [key: string]: unknown;
            };
            format?: components["schemas"]["ResourceFormat"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Importance
             * @default 3
             */
            importance: number;
            /**
             * In Core
             * @default false
             */
            in_core: boolean;
            /**
             * In Quick
             * @default false
             */
            in_quick: boolean;
            kind: components["schemas"]["Kind"];
            /** Last Accessed At */
            last_accessed_at?: string | null;
            /**
             * Mentioned At
             * Format: date-time
             */
            mentioned_at: string;
            /** @default asserted */
            modality: components["schemas"]["Modality"];
            /** Occurred End */
            occurred_end?: string | null;
            /** Occurred Start */
            occurred_start?: string | null;
            /** Predicate */
            predicate?: string | null;
            /** Quick Reason */
            quick_reason?: string | null;
            /** Quick Until */
            quick_until?: string | null;
            /** Rating */
            rating?: {
                [key: string]: number;
            } | null;
            /** Rationale */
            rationale?: string | null;
            /** Raw Content */
            raw_content?: string | null;
            /** Rrule */
            rrule?: string | null;
            /** @default normal */
            sensitivity: components["schemas"]["Sensitivity"];
            /** Sentiment */
            sentiment?: number | null;
            /** @default user_message */
            source: components["schemas"]["Source"];
            /** State */
            state: string;
            /** @default active */
            status: components["schemas"]["ItemStatus"];
            /** Subject Entity Id */
            subject_entity_id?: string | null;
            /** Subtype */
            subtype?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Text */
            text: string;
            time_precision?: components["schemas"]["TimePrecision"] | null;
            /** Title */
            title: string;
            /** @default user_stated */
            trust: components["schemas"]["Trust"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Updated By Turn Id
             * Format: uuid
             */
            updated_by_turn_id: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Value */
            value?: {
                [key: string]: unknown;
            } | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * ItemStatus
         * @description About the record ("deleted"), not the world (that is ``state``).
         * @enum {string}
         */
        ItemStatus: "active" | "archived" | "deleted";
        /**
         * Kind
         * @description What a memory is, defined by how it behaves over time.
         * @enum {string}
         */
        Kind: "fact" | "preference" | "episode" | "plan" | "task" | "intention" | "resource" | "note" | "rule" | "pattern";
        /**
         * Layer
         * @enum {string}
         */
        Layer: "core" | "quick" | "archive";
        /** LinkRecord */
        LinkRecord: {
            /**
             * Created By Turn Id
             * Format: uuid
             */
            created_by_turn_id: string;
            /**
             * Dst Item Id
             * Format: uuid
             */
            dst_item_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            link_type: components["schemas"]["LinkType"];
            /**
             * Src Item Id
             * Format: uuid
             */
            src_item_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * LinkType
         * @enum {string}
         */
        LinkType: "supersedes" | "fulfils" | "part_of" | "follows" | "because" | "evidence_for" | "duplicate_of" | "derived_from" | "gift_for_event";
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceOut"][];
        };
        /**
         * MemoryDiffEvent
         * @description Memory diff panel, built from the write log so it can't disagree with what happened.
         */
        MemoryDiffEvent: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["DiffEntry"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "memory_diff";
            /** Undo Of */
            undo_of?: string | null;
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /** MetaOut */
        MetaOut: {
            /** Config Hash */
            config_hash: string;
            /** Config Hash Short */
            config_hash_short: string;
            /** Dev Auth */
            dev_auth: boolean;
            /** Env */
            env: string;
            /** Name */
            name: string;
            /** Price Version */
            price_version: string;
            /** Prompts */
            prompts: string[];
            /** Provider Mode */
            provider_mode: string;
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            /** Substitutions */
            substitutions: string[];
            /** Tracing Enabled */
            tracing_enabled: boolean;
            /** Version */
            version: string;
        };
        /**
         * Modality
         * @enum {string}
         */
        Modality: "asserted" | "planned" | "hypothetical" | "reported";
        /**
         * ModelCallEvent
         * @description One model call: who served it, what it cost, how long it took (FR-14.8, FR-19.2).
         */
        ModelCallEvent: {
            /** Attempts */
            attempts: number;
            /**
             * Cache Hits
             * @description Embeddings reused from the content-hash cache (FR-14.6).
             */
            cache_hits?: number | null;
            fallback?: components["schemas"]["FallbackInfo"] | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Prompt */
            prompt?: string | null;
            /** Provider */
            provider: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Step */
            step: string;
            /** Time To First Token Ms */
            time_to_first_token_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "model_call";
            usage: components["schemas"]["Usage"];
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /**
         * Normalisation
         * @description A slug the model proposed, and what normalisation chose (reuse beats invention).
         */
        Normalisation: {
            /** Chosen */
            chosen: string;
            /**
             * How
             * @default
             */
            how: string;
            /** Proposed */
            proposed: string;
            /** Reused */
            reused: boolean;
            /**
             * Vocab
             * @enum {string}
             */
            vocab: "category" | "subtype" | "predicate" | "relation";
        };
        /**
         * PolicyDecision
         * @enum {string}
         */
        PolicyDecision: "allowed" | "held" | "blocked";
        /**
         * PolicyEvent
         * @description A write-policy decision on one proposed operation (FR-4.6).
         */
        PolicyEvent: {
            /** Op */
            op: string;
            /** Target */
            target?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "policy";
            /**
             * V
             * @default 1
             */
            v: number;
            verdict: components["schemas"]["PolicyVerdict"];
        };
        /** PolicyVerdict */
        PolicyVerdict: {
            decision: components["schemas"]["PolicyDecision"];
            /** Reason */
            reason: string;
            /** Rule Id */
            rule_id: string;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckOut"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * ReconcileDecision
         * @enum {string}
         */
        ReconcileDecision: "new" | "add_detail" | "supersede" | "fulfil" | "link" | "no_op";
        /**
         * ReconcileInfo
         * @description How a proposed memory relates to what is stored (S2.8).
         */
        ReconcileInfo: {
            /** Candidate Id */
            candidate_id?: string | null;
            /** Candidate Title */
            candidate_title?: string | null;
            decision: components["schemas"]["ReconcileDecision"];
            /**
             * Rule
             * @default
             */
            rule: string;
            /** Score */
            score?: number | null;
        };
        /** Reconciliation */
        Reconciliation: {
            info: components["schemas"]["ReconcileInfo"];
            /** Label */
            label: string;
        };
        /**
         * ResourceFormat
         * @enum {string}
         */
        ResourceFormat: "article" | "video" | "pdf" | "image" | "link" | "other";
        /** RetrievalCandidate */
        RetrievalCandidate: {
            /** Dense Score */
            dense_score?: number | null;
            /** Fused Score */
            fused_score?: number | null;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            layer: components["schemas"]["Layer"];
            /** Lexical Score */
            lexical_score?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Rerank Score */
            rerank_score?: number | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /** Title */
            title: string;
        };
        /**
         * RetrievalEvent
         * @description Retrieval panel: plan, filters, candidates with scores, what reached the answer.
         */
        RetrievalEvent: {
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["RetrievalCandidate"][];
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /**
             * Filters
             * @default {}
             */
            filters: {
                [key: string]: string;
            };
            /**
             * Layers
             * @default []
             */
            layers: components["schemas"]["Layer"][];
            /** Query */
            query: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "retrieval";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /** RouteOut */
        RouteOut: {
            /** Fallback */
            fallback: string | null;
            /** Model */
            model: string;
            /** Prompt */
            prompt: string | null;
            /** Provider */
            provider: string;
            /** Step */
            step: string;
            /** Timeout S */
            timeout_s: number;
        };
        /**
         * Sensitivity
         * @enum {string}
         */
        Sensitivity: "normal" | "personal" | "sensitive" | "secret";
        /**
         * Source
         * @enum {string}
         */
        Source: "user_message" | "link" | "file" | "derived";
        /**
         * SseStepStarted
         * @description An agent step began (ADR-0029). Its ``step`` event follows in a ``turn.event`` frame.
         */
        SseStepStarted: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            step: components["schemas"]["AgentStep"];
        };
        /** SseToken */
        SseToken: {
            /** Text */
            text: string;
        };
        /** SseTurnCompleted */
        SseTurnCompleted: {
            /**
             * @description The user's quota after this turn (null if it can't be read).
             * @default null
             */
            quota: components["schemas"]["UsageOut"] | null;
            turn: components["schemas"]["TurnOut"];
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            usage: components["schemas"]["UsageTotals"];
        };
        /**
         * SseTurnEvent
         * @description A turn event, as it was persisted (the same ``seq`` and body as ``/events``).
         */
        SseTurnEvent: {
            /** Event */
            event: components["schemas"]["IntentEvent"] | components["schemas"]["DecisionEvent"] | components["schemas"]["MemoryDiffEvent"] | components["schemas"]["RetrievalEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["PolicyEvent"] | components["schemas"]["ModelCallEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["StepEvent"];
            /** Seq */
            seq: number;
        };
        /** SseTurnFailed */
        SseTurnFailed: {
            error: components["schemas"]["TurnError"];
            /**
             * @description The user's quota after this turn (null if it can't be read).
             * @default null
             */
            quota: components["schemas"]["UsageOut"] | null;
            turn: components["schemas"]["TurnOut"];
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            usage: components["schemas"]["UsageTotals"];
        };
        /** SseTurnStarted */
        SseTurnStarted: {
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * StepEvent
         * @description One agent step that ran: how it ended and how long it took (ADR-0029).
         */
        StepEvent: {
            /** Latency Ms */
            latency_ms: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["StepStatus"];
            step: components["schemas"]["AgentStep"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /**
         * StepModel
         * @description Which provider and model served a step, and with which prompt version (FR-19.2).
         */
        StepModel: {
            /** Fallback From */
            fallback_from?: string | null;
            /** Model */
            model: string;
            /** Prompt */
            prompt?: string | null;
            /** Provider */
            provider: string;
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "done" | "held" | "refused" | "failed";
        /**
         * Tier
         * @enum {string}
         */
        Tier: "guest" | "standard" | "premium";
        /**
         * TimeClock
         * @description Which clock a time expression sets: when it happened, when it was true, when it is due,
         *     or when to remind.
         * @enum {string}
         */
        TimeClock: "occurred" | "valid" | "due" | "trigger";
        /**
         * TimePrecision
         * @enum {string}
         */
        TimePrecision: "datetime" | "day" | "month" | "year";
        /**
         * TimeResolution
         * @description One time expression, resolved by code (never the model): expression -> value.
         */
        TimeResolution: {
            /** Alternative */
            alternative?: string | null;
            /**
             * Assumed
             * @default false
             */
            assumed: boolean;
            clock: components["schemas"]["TimeClock"];
            /** End */
            end?: string | null;
            /** Expression */
            expression: string;
            /** Memory */
            memory?: string | null;
            /**
             * Now
             * Format: date-time
             */
            now: string;
            precision: components["schemas"]["TimePrecision"];
            /** Rrule */
            rrule?: string | null;
            /** Rule */
            rule: string;
            /** Timezone */
            timezone: string;
            /** Value */
            value: string;
        };
        /**
         * ToolCallEvent
         * @description Tool calls panel: tool, summarised arguments and result, policy verdict.
         */
        ToolCallEvent: {
            /**
             * Arguments
             * @default {}
             */
            arguments: {
                [key: string]: string;
            };
            /** Latency Ms */
            latency_ms?: number | null;
            policy?: components["schemas"]["PolicyVerdict"] | null;
            /**
             * Result Summary
             * @default
             */
            result_summary: string;
            /** Tool */
            tool: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_call";
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /** TraceLink */
        TraceLink: {
            status: components["schemas"]["TraceStatus"];
            /**
             * Url
             * @description Link to the raw trace; null when unavailable or disabled.
             */
            url?: string | null;
        };
        /**
         * TraceStatus
         * @description Whether the turn's trace reached the trace backend (FR-9.2).
         * @enum {string}
         */
        TraceStatus: "recorded" | "unavailable" | "disabled";
        /**
         * TriggerOn
         * @enum {string}
         */
        TriggerOn: "time" | "person" | "place" | "topic" | "situation";
        /** TriggerRecord */
        TriggerRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By Turn Id
             * Format: uuid
             */
            created_by_turn_id: string;
            /** Expires At */
            expires_at?: string | null;
            /** Fires At */
            fires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** @default time */
            on: components["schemas"]["TriggerOn"];
            /**
             * Spec
             * @default {}
             */
            spec: {
                [key: string]: unknown;
            };
            /** @default pending */
            state: components["schemas"]["TriggerState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Updated By Turn Id
             * Format: uuid
             */
            updated_by_turn_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * TriggerState
         * @enum {string}
         */
        TriggerState: "pending" | "fired" | "done" | "cancelled" | "expired";
        /**
         * Trust
         * @enum {string}
         */
        Trust: "user_stated" | "content_derived";
        /** TurnError */
        TurnError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** TurnEventOut */
        TurnEventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event */
            event: components["schemas"]["IntentEvent"] | components["schemas"]["DecisionEvent"] | components["schemas"]["MemoryDiffEvent"] | components["schemas"]["RetrievalEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["PolicyEvent"] | components["schemas"]["ModelCallEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["StepEvent"];
            /** Seq */
            seq: number;
        };
        /** TurnEventsOut */
        TurnEventsOut: {
            /**
             * Events
             * @description In emission order (seq ascending).
             */
            events: components["schemas"]["TurnEventOut"][];
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
        };
        /**
         * TurnKind
         * @description What started a turn: a message, an undo, a confirmation of a held write, or the system
         *     (background jobs). Every kind is stored, auditable and undoable the same way.
         * @enum {string}
         */
        TurnKind: "user" | "undo" | "confirm" | "system";
        /** TurnOut */
        TurnOut: {
            /** Config Hash */
            config_hash: string;
            error?: components["schemas"]["TurnError"] | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: string;
            /**
             * @description user (a message), undo, confirm (a held write) or system (a background job).
             * @default user
             */
            kind: components["schemas"]["TurnKind"];
            /** Models */
            models: {
                [key: string]: components["schemas"]["StepModel"];
            };
            /** Output */
            output: string | null;
            /**
             * Parent Turn Id
             * @description The undone turn, or the turn whose held write was confirmed.
             */
            parent_turn_id?: string | null;
            /** Prompt Versions */
            prompt_versions: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["TurnStatus"];
            trace: components["schemas"]["TraceLink"];
            usage: components["schemas"]["UsageTotals"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** TurnPage */
        TurnPage: {
            /**
             * Items
             * @description Newest first.
             */
            items: components["schemas"]["TurnOut"][];
            /**
             * Next Before
             * @description Pass as `before` to get the next (older) page.
             */
            next_before?: string | null;
        };
        /**
         * TurnStatus
         * @enum {string}
         */
        TurnStatus: "running" | "completed" | "failed";
        /**
         * TurnStreamFrame
         * @description One server-sent event on the turn stream: `event:` name, `data:` JSON.
         */
        TurnStreamFrame: {
            data: components["schemas"]["SseTurnStarted"];
            /** @constant */
            event: "turn.started";
        } | {
            data: components["schemas"]["SseToken"];
            /** @constant */
            event: "token";
        } | {
            data: components["schemas"]["SseStepStarted"];
            /** @constant */
            event: "step.started";
        } | {
            data: components["schemas"]["SseTurnEvent"];
            /** @constant */
            event: "turn.event";
        } | {
            data: components["schemas"]["SseTurnCompleted"];
            /** @constant */
            event: "turn.completed";
        } | {
            data: components["schemas"]["SseTurnFailed"];
            /** @constant */
            event: "turn.failed";
        };
        /**
         * Usage
         * @description Usage of one model call.
         *
         *     ``input_tokens`` counts *uncached* input only; cached reads are in ``cached_input_tokens``.
         *     Adapters normalise to this split so cost is always
         *     ``input * p_in + cached * p_cached + output * p_out`` from the price table.
         */
        Usage: {
            /**
             * Cached Input Tokens
             * @default 0
             */
            cached_input_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Price Version */
            price_version: string;
            /** Provider */
            provider: string;
        };
        /**
         * UsageOut
         * @description The signed-in user's token quota, as it stands now (FR-12.5). Read only until S4.
         */
        UsageOut: {
            /** Limit Tokens */
            limit_tokens: number;
            /** Remaining Tokens */
            remaining_tokens: number;
            tier: components["schemas"]["Tier"];
            /** Used Tokens */
            used_tokens: number;
        };
        /**
         * UsageTotals
         * @description Sum of usage across a turn's model calls.
         */
        UsageTotals: {
            /**
             * Cached Input Tokens
             * @default 0
             */
            cached_input_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * WorkspaceKind
         * @enum {string}
         */
        WorkspaceKind: "private" | "guest" | "persona_copy";
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["WorkspaceKind"];
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description A dependency is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    dev_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevLoginIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_held_write: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                held_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_held_write: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                held_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeldWriteOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    my_usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    get_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_turn_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnEventsOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undo_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_held_writes: {
        parameters: {
            query?: {
                status?: ("pending" | "confirmed" | "rejected") | null;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeldWritesOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_turns: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Turn id to page from */
                before?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnPage"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTurnIn"];
            };
        };
        responses: {
            /** @description A `text/event-stream` of frames: `turn.started`, then `token`, `step.started` and `turn.event` (each repeated, in the order they happened), then exactly one of `turn.completed` or `turn.failed`. Comment lines are keep-alives. Clients may ignore `step.started` and `turn.event`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TurnStreamFrame"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
