#!/usr/bin/env bash
# Write .prodlike.env (gitignored, mode 600): the values `make up-prodlike` gives the production
# compose file (compose.prodlike.yaml). It keeps what it generated before (session secret, access
# code, passwords), so the rehearsal's volumes keep working, takes the two provider keys from
# .env when it has them, and sets everything else to what the rehearsal needs.
#
# Only the provider keys are copied from .env: a developer's .env carries local defaults
# (example secrets, the self-hosted Langfuse) that production refuses.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
file="$root/.prodlike.env"
umask 077

get() { # get FILE KEY: the value of KEY=… in FILE, or nothing
  [[ -f "$1" ]] || return 0
  sed -n "s/^$2=//p" "$1" | tail -n 1
}
secret() { openssl rand -hex "${1:-24}"; }

session="$(get "$file" SESSION_SECRET)"
[[ -n "$session" ]] || session="$(get "$file" PRODLIKE_SESSION_SECRET)"
code="$(get "$file" ACCESS_CODE)"
[[ -n "$code" ]] || code="$(get "$file" PRODLIKE_ACCESS_CODE)"
owner="$(get "$file" POSTGRES_PASSWORD)"
app="$(get "$file" APP_DB_PASSWORD)"
redis="$(get "$file" REDIS_PASSWORD)"

{
  echo "# Generated by scripts/prodlike-env.sh for \`make up-prodlike\`. Gitignored; safe to delete"
  echo "# (delete the rehearsal's volumes with \`make clean-prodlike\` too)."
  echo "SESSION_SECRET=${session:-$(secret 32)}"
  echo "ACCESS_CODE=${code:-$(secret 6)}"
  echo "POSTGRES_PASSWORD=${owner:-$(secret)}"
  echo "APP_DB_PASSWORD=${app:-$(secret)}"
  echo "REDIS_PASSWORD=${redis:-$(secret)}"
  # Provider keys, from the developer's .env when there is one (production reads them from SSM).
  for key in ANTHROPIC_API_KEY OPENAI_API_KEY; do
    value="$(get "$root/.env" "$key")"
    [[ -z "$value" ]] || echo "$key=$value"
  done
  # The rehearsal's own address: a local certificate for localhost, on ports that don't collide
  # with `make up` (web on 8080).
  echo "APP_HOST=localhost"
  echo "EDGE_HTTP_PORT=8081"
  echo "EDGE_HTTPS_PORT=8443"
  echo "ALLOWED_ORIGINS=https://localhost:8443"
  echo "TRACING_ENABLED=false"
  echo "SPEND_CAP_DAILY_USD=0.50"
  echo "SPEND_CAP_MONTHLY_USD=5"
} > "$file.tmp"
mv "$file.tmp" "$file"
echo "wrote $file (gitignored)" >&2
